# Site settings
title: thisisyojan/blog 
email: thisisyojan@gmail.com 
description: "We're all spiders weaving the web." 
baseurl: ""
url: "http://sinkingshriek.github.io"
twitter-username: shri3k
github-username: sinkingshriek/jekyll-content


# Build settings
markdown: kramdown
permalink: pretty
